[versions]
koinAndroid = "4.2.0-RC1"
koinCompiler = "0.3.0"
kotlin = "2.3.20-RC"
serializationJson = "1.10.0"
agp = "9.0.1"
navigation3Runtime = "1.0.1"
material3 = "1.4.0" #is already the latest stable version
navigation3Ui = "1.0.1"
retrofit = "3.0.0"

[libraries]

koin-android = { module = "io.insert-koin:koin-android", version.ref = "koinAndroid" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koinAndroid" }
koin-compose-navigation3 = { module = "io.insert-koin:koin-compose-navigation3", version.ref = "koinAndroid" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serializationJson" }
material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "material3" }
navigation3-runtime = { group = "androidx.navigation3", name = "navigation3-runtime", version.ref = "navigation3Runtime" }
navigation3-ui = { group = "androidx.navigation3", name = "navigation3-ui", version.ref = "navigation3Ui" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
gson-converter = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
koin-compiler = { id = "io.insert-koin.compiler.plugin", version.ref = "koinCompiler" }
